# Configuration file for HomeSpawnWarp.


# The option useExactSpawn lets you choose if you want to use
# Craftbukkit's playerspawning system or my custom made one. If you set
# useExactSpawn it will use my one and you will exactly spawn at the spawnpoint.
# I highly recommend you to set this option to true.

# The option useGeneralSpawn lets you choose between one spawn per world or one general spawn.

# More information at http://dev.bukkit.org/bukkit-mods/homespawnwarp

useexactspawn: true
usegeneralspawn: true
usefireworkeffects: true
cancelwarmupsonmove: false

# Warmup time in seconds per command. Specify a negative or zero number
# to disable warmup for this command. You can bypass players from having
# to warmup by giving them the HomeSpawnWarp.nowarmup permission.
warmups:
  home: 0
  spawn: 0
  warp: 0
  request: 0
  
# Prices for commands. You can bypass players from paying money 
# by giving them the HomeSpawnWarp.nofee permission.
prices:
  home1: 0
  home2: 0
  home3: 0
  home4: 0
  home5: 0
  spawn1: 0
  spawn2: 0
  spawn3: 0
  spawn4: 0
  spawn5: 0
  warp1: 0
  warp2: 0
  warp3: 0
  warp4: 0
  warp5: 0
  warpto1: 0
  warpto2: 0
  warpto3: 0
  warpto4: 0
  warpto5: 0


# Homegroups, specifies how many homes a group is allowed to have.
homelimits:
  group1: 1
  group2: 2
  group3: 3
  group4: 5
  group5: 10
