name: HomeSpawnWarp
main: com.homespawnwarp.plugin.HomeSpawnWarp
version: 0.9.2
description: HomeSpawnWarp Beta
author: pieter3457
softdepend: [Vault]
website: http://dev.bukkit.org/bukkit-plugins/homespawnwarp/
commands:
  sethome:
    description: Set your home to your current position.
  home:
    description: Go to your with /sethome set home.
  homelist:
    description: Prints out all your homes.
  delhome:
    description: Deletes the given home.
  setspawn:
    description: Set the worldspawn.
  spawn:
    description: Go to the worldspawn.
  setwarp:
    description: Set a public warp.
  warp:
    description: Warp to a warplocation.
  delwarp:
    description: Remove a warp.
  warplist:
    description: View a list of available warps.
  warpto:
    description: Sends the specified player a warpto request.
  warphere:
    description: Sends the specified player a warphere request.
  warpaccept:
    description: Accepts a warpto request.
